In [2]:
import numpy as np

ARRAY OPERATION

In [4]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [ ]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [8]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [9]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [10]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [11]:
a1// a2

array([0, 0, 0, 0, 0])

In [12]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [20]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

BROADCASTING

In [14]:
l = [10,20,30,40]
arr = np.array(l)

In [15]:
arr + 10

array([20, 30, 40, 50])

In [16]:
arr= np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [17]:
arr +10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

DEEP AND SHALLOW COPY

In [21]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [25]:
slice = a[0:5]
slice = slice*10
slice

array([10, 20, 30, 40, 50])

In [26]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [28]:
a[4:6] *10

array([50, 60])

In [29]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [37]:
a
b = a

In [38]:
b[0] = 99

In [39]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [40]:
a 
b = a.copy()

In [41]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [42]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

MATRIX OPERATION

In [44]:
A = np.array([[1,2] , [3,4]])
B = np.array([[5,6],[7,8]])

In [45]:
A

array([[1, 2],
       [3, 4]])

In [46]:
B

array([[5, 6],
       [7, 8]])

In [48]:
A @ B

array([[19, 22],
       [43, 50]])

In [49]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [50]:
A.T

array([[1, 3],
       [2, 4]])

ADVANCE ARRAY MANIPULATION

Stacking array

In [51]:
A

array([[1, 2],
       [3, 4]])

In [52]:
B

array([[5, 6],
       [7, 8]])

In [58]:
a = np.array([1,2 ,3,4])
b = np.array([5,6,7,8])

In [59]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [60]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [61]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Spliting Array

In [62]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [68]:
a=np.hsplit(c,2)

In [70]:
a = np.vsplit(c,4)

In [71]:
for i in a:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
