In [7]:
import numpy as np



In [8]:
arr  = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [9]:
a = [1,2,3,4.5,"hello"]
a

[1, 2, 3, 4.5, 'hello']

In [10]:
np.array(a)

array(['1', '2', '3', '4.5', 'hello'], dtype='<U32')

In [11]:
l =[1,2,3] ,[4,5,6],[7,8,9]

In [12]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array generation function

In [13]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [14]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [16]:
arr = np.linspace(1,5,3)
arr 

array([1., 3., 5.])

Random genration function

In [17]:
np.random.rand(5)

array([0.11721441, 0.26644649, 0.91822521, 0.01125435, 0.84547579])

In [18]:
np.random.randn(10)

array([ 1.58865346, -0.6094704 , -1.01427506,  0.35506194,  1.4901614 ,
       -0.5386613 ,  1.08039223, -0.51106824, -0.48254612,  1.28768911])

In [19]:
np.random.randint(10,20,10)

array([19, 14, 11, 17, 12, 14, 12, 11, 11, 18], dtype=int32)

array attributes

In [20]:
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr.shape

(3, 3)

In [22]:
arr.size

9

In [23]:
arr.dtype

dtype('int64')

array method

In [24]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
arr.min()

np.int64(1)

In [26]:
arr.max()

np.int64(9)

In [27]:
arr.sum()

np.int64(45)

In [30]:
np.sum(arr,axis= 0)

array([12, 15, 18])

In [31]:
np.sum(arr,axis = 1)

array([ 6, 15, 24])

In [32]:
arr.mean()

np.float64(5.0)

In [33]:
arr.std()

np.float64(2.581988897471611)

In [34]:
arr.argmin()

np.int64(0)

reshaping and resizing

In [35]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr = arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])