In [1]:
import numpy as np

NUMPY INDEXING AND SLICING OF VECTORS

In [4]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
arr[6]

np.int64(17)

In [10]:
arr_slice = arr[1:5]
arr_slice

array([12, 13, 14, 15])

In [7]:
arr[:5]

array([11, 12, 13, 14, 15])

In [8]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [9]:
arr[3::2]

array([14, 16, 18, 20])

NUMPY INDEXING AND SLICING OF MATRIX

In [11]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [12]:
arr[0]

array([1, 2, 3, 4, 5])