In [ ]:
import numpy as np



In [2]:
arr  = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
a = [1,2,3,4.5,"hello"]
a

[1, 2, 3, 4.5, 'hello']

In [4]:
np.array(a)

array(['1', '2', '3', '4.5', 'hello'], dtype='<U32')

In [5]:
l =[1,2,3] ,[4,5,6],[7,8,9]

In [6]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array generation function

In [7]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [10]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [14]:
arr = np.linspace(1,5,3)
arr 

array([1., 3., 5.])

Random genration function