indexing and slicing

In [1]:
import numpy as np

In [6]:
arr = np.array([10,20,30,40,50,60])
arr

array([10, 20, 30, 40, 50, 60])

In [3]:
arr[1:5]

array([20, 30, 40, 50])

In [10]:
arr= arr[-1:0]
arr

array([], dtype=int64)

In [11]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr[1]

array([4, 5, 6])

In [13]:
arr[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
slice = arr[:,2]
slice

array([3, 6, 9])

In [16]:
arr[1:1]

array([], shape=(0, 3), dtype=int64)

In [17]:
slice = arr[1,1]
slice

np.int64(5)

In [18]:
arr = np.array([11,22,33,44,55,66,77,88,99])
arr

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [20]:
boolean = arr%2==0
boolean

array([False,  True, False,  True, False,  True, False,  True, False])

In [21]:
arr = arr[boolean]
arr

array([22, 44, 66, 88])