In [1]:
import numpy as np

In [2]:
arr = np.array([2,4,6,8,10])
arr

array([ 2,  4,  6,  8, 10])

In [3]:
arr + 5

array([ 7,  9, 11, 13, 15])

In [4]:
arr * 3

array([ 6, 12, 18, 24, 30])

In [5]:
arr*arr

array([  4,  16,  36,  64, 100])

In [6]:
arr = np.array([12,25,8,40,15])
arr

array([12, 25,  8, 40, 15])

In [8]:
arr.max()

np.int64(40)

In [9]:
arr.min()

np.int64(8)

In [11]:
arr.mean()

np.float64(20.0)

In [10]:
arr.sum()

np.int64(100)

In [12]:
arr.std()

np.float64(11.47170431975999)

In [18]:
arr = np.array([10,30,20,40,15,50])
arr

array([10, 30, 20, 40, 15, 50])

In [19]:
arr[arr > 25] = 0
arr

array([10,  0, 20,  0, 15,  0])

In [20]:
arr = np.array([45,12,78,9,23,56])
arr

array([45, 12, 78,  9, 23, 56])

In [25]:
arr = np.sort(arr)
arr

array([ 9, 12, 23, 45, 56, 78])

In [27]:
arr = np.sort(arr)[::-1]
arr

array([78, 56, 45, 23, 12,  9])

In [28]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [29]:
c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6])