In [24]:
import numpy as np

In [5]:
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [7]:
arr.shape

(5,)

In [8]:
arr.size

5

In [10]:
arr.dtype

dtype('int64')

In [11]:
arr.ndim

1

In [22]:
arr = np.array([[1,2,3] , [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
arr = np.ones((2,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])