In [48]:
import numpy as np

In [49]:
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [50]:
arr.shape

(5,)

In [51]:
arr.size

5

In [52]:
arr.dtype

dtype('int64')

In [53]:
arr.ndim

1

In [54]:
arr = np.array([[1,2,3] , [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [56]:
arr = np.ones((2,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [57]:
arr 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [58]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [59]:
arr.reshape([3,4])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [61]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [62]:
arr[0:6:3]


array([[ 1,  2,  3],
       [10, 11, 12]])